### ISSUE TITLE
Create a Cost Management Budget/Alert 

### ISSUE THREAD

**Issue by brandonmartinez** [joshuawaddell/azure-demo-environment#157]
Setting a moderate threshold in Cost Management would keep end users in the know of what ADE is actually costing them. Thresholds could be staged at $50/100/250/500/1000 tiers.

Doc: https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/quick-create-budget-template?tabs=CLI

**Comment by joshuawaddell** [comment]
Completed.
