### ISSUE TITLE
Replace WordPress Deployment with Minecraft

### ISSUE THREAD

**Issue by brandonmartinez** [joshuawaddell/azure-demo-environment#70]
Minecraft can run via docker; replace Wordpress with Minecraft.

**Comment by joshuawaddell** [comment]
https://github.com/sjkp/azure-arm-aci-minecraft-server/blob/master/azuredeploy.json

**Comment by brandonmartinez** [comment]
Going to remove this as we have other things to use ACI that are part of the new app.
